# Use a specific version of Python
FROM python:3.12

LABEL maintainer="front_end"

# Set the working directory in the container
WORKDIR /code

# Install system dependencies required for potential Python packages
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# Install Poetry with a pinned version
RUN pip install poetry

# Copy the current directory contents into the container at /code
COPY . /code/

# Configuration to avoid creating virtual environments inside the Docker container
RUN poetry config virtualenvs.create false 

# Install dependencies including development ones
RUN poetry install 


# Make port 8501 available to the world outside this container
EXPOSE 8501

ENV API_URL=http://api_dev1:8000

# Run the app. CMD can be overridden when starting the container
CMD ["poetry", "run", "streamlit", "run", "./front_end/main.py", "--server.port=8501", "--server.enableCORS=false", "--server.enableXsrfProtection=false"]
